-- Create messages table
CREATE TABLE messages (
    id INT NOT NULL PRIMARY KEY, -- MySQL: INT NOT NULL AUTO_INCREMENT PRIMARY KEY
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
